//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demoapp.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.OrderProes = new HashSet<OrderPro>();
        }


        [Display(Name = "ID User")]
        public int IDCus { get; set; }

        [DisplayName("Tên")]
        [Required(ErrorMessage = "không được bỏ trống")]
        public string NameCus { get; set; }

        [DisplayName("Mật Khẩu")]
        [Required(ErrorMessage = "không được bỏ trống")]
        public string Password { get; set; }

        [DisplayName("Số điện thoại")]
        [Required(ErrorMessage = "không được bỏ trống")]
        public string PhoneCus { get; set; }

        [DisplayName("Email")]
        [Required(ErrorMessage = "không được bỏ trống")]
        public string EmailCus { get; set; }

        [DisplayName("Địa Chỉ")]
        [Required(ErrorMessage = "không được bỏ trống")]
        public string AddrCus { get; set; }

        [DisplayName("Ảnh")]
        public string ImgCus { get; set; }

        [NotMapped]
        [DisplayName("Nhập lại mật khẩu")]
        [Required(ErrorMessage = "Không được bỏ trống")]
        [Compare("Password")]
        public string Repass { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderPro> OrderProes { get; set; }
    }
}
