//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demoapp.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            ImagePro1 = "~/Content/Images/Home1.jpg";
            ImagePro2 = "~/Content/Images/Home1.jpg";
            ImagePro3 = "~/Content/Images/Home1.jpg";
            ImagePro4 = "~/Content/Images/Home1.jpg";
            this.OrderDetails = new HashSet<OrderDetail>();
        }

        [DisplayName("ID")]
        public int ProductID { get; set; }
        [DisplayName("Tên sản phẩm")]
        public string NamePro { get; set; }
        [DisplayName("giới thiệu sản phẩm")]
        public string DecriptionPro { get; set; }
        [DisplayName("Mã sản phẩm")]
        public string Category { get; set; }
        [DisplayName("Giá")]
        public Nullable<decimal> Price { get; set; }
        [DisplayName("giảm giá")]
        public Nullable<decimal> Discount { get; set; }
        public string ImagePro1 { get; set; }
        public string ImagePro2 { get; set; }
        public string ImagePro3 { get; set; }
        public string ImagePro4 { get; set; }
        [DisplayName("bộ sưu tập")]
        public string Collection { get; set; }  
        public virtual Category Category1 { get; set; }
        public virtual Collection Collection1 { get; set; }      
       
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        [NotMapped]
        public HttpPostedFileBase ImageUpload1 { get; set; }
        [NotMapped]
        public HttpPostedFileBase ImageUpload2 { get; set; }
        [NotMapped]
        public HttpPostedFileBase ImageUpload3 { get; set; }
        [NotMapped]
        public HttpPostedFileBase ImageUpload4 { get; set; }
    }
}
